import { build } from "esbuild"
import { mkdir } from "fs/promises"
import { homedir } from "os"
import { dirname, join, resolve } from "path"
import { fileURLToPath } from "url"
import { managedTools } from "../src/tools/index.js"

interface DeployTarget {
  name: string
  outfile: string
}

const scriptDir = dirname(fileURLToPath(import.meta.url))
const ecosystemRoot = resolve(scriptDir, "..")
const projectRoot = resolve(ecosystemRoot, "..")

const target = readOption("--target") ?? "local"
const explicitOutDir = readOption("--out-dir")
const outDir = explicitOutDir ?? defaultOutDir(target)

const tools: DeployTarget[] = managedTools.map(tool => ({
  name: tool.name,
  outfile: join(outDir, `${tool.name}.js`),
}))

const duplicate = findDuplicate(tools.map(tool => tool.name))
if (duplicate) throw new Error(`Duplicate tool name: ${duplicate}`)

await mkdir(outDir, { recursive: true })

for (const tool of tools) {
  await build({
    stdin: {
      contents: opencodeEntryFor(tool.name),
      resolveDir: ecosystemRoot,
      sourcefile: `generated-opencode-${tool.name}.ts`,
      loader: "ts",
    },
    outfile: tool.outfile,
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node20",
    sourcemap: false,
    minify: false,
    treeShaking: true,
    banner: {
      js: [
        "// Generated by ecosystem/scripts/deploy-opencode-tools.ts.",
        "// Do not edit this file directly; edit ecosystem/src/tools/* instead.",
      ].join("\n"),
    },
  })
  console.log(`[tools:deploy] ${tool.name} -> ${tool.outfile}`)
}

function opencodeEntryFor(toolName: string): string {
  return [
    `import { createOpenCodeTool } from "./src/tools/opencode/opencodeAdapter.js"`,
    `import { managedTools } from "./src/tools/index.js"`,
    ``,
    `const definition = managedTools.find(tool => tool.name === ${JSON.stringify(toolName)})`,
    `if (!definition) throw new Error("Tool not found: ${toolName}")`,
    `export default createOpenCodeTool(definition)`,
  ].join("\n")
}

function readOption(name: string): string | undefined {
  const rawArgs = process.argv.slice(2)
  for (let index = 0; index < rawArgs.length; index += 1) {
    const value = rawArgs[index]
    if (value === name) return rawArgs[index + 1]
    if (value?.startsWith(`${name}=`)) return value.slice(name.length + 1)
  }
  return undefined
}

function defaultOutDir(targetName: string): string {
  if (targetName === "local") return join(projectRoot, ".opencode", "tools")
  if (targetName === "global") {
    const configRoot = process.env.OPENCODE_CONFIG_DIR ?? join(homedir(), ".config", "opencode")
    return join(configRoot, "tools")
  }
  throw new Error(`Unsupported --target ${targetName}. Use local, global, or --out-dir.`)
}

function findDuplicate(values: string[]): string | undefined {
  const seen = new Set<string>()
  for (const value of values) {
    if (seen.has(value)) return value
    seen.add(value)
  }
  return undefined
}
